feat: metadata api
LiquidX-Studio/Fast-metadata-service pull request #1
Opened 2023-02-01 02:08 UTC by KY64

This PR contains code for a minimal metadata service. This metadata service only has 3 endpoints:

- `/health`: for health checking
- `/metadata/{token}`: for getting metadata from particular token ID, `{token}` should be replaced with integer such as 1, 2, 3, etc.
- `/internal/update/metadata/{token}`: for updating metadata from particular ID, `{token}` should be replaced with integer such as 1, 2, 3, etc.

Design document https://github.com/Pixelation-Labs/pixelmon-project-design-documents/pull/11

## Rationale

Storing metadata in the cloud storage or distributed storage is a common practice if we want the metadata of an NFT to be persistence and immutable. However, sometimes we want to do more like unreveal some NFT that's not been claimed, update the metadata with new attributes or key, etc. This metadata service is built with that purpose. Although it only has 3 endpoints, this metadata service can be a building block to extend more features in it. So instead of writing from scratch to add feature to read cloud storage or create an abstraction in a way so it's easy to extend it, we write our opinionated version of metadata service so that we can add more endpoints and logic in it.

## Test

```
----------------------------------------------------------------------
Ran 69 tests in 0.182s

OK
Name                                           Stmts   Miss  Cover
------------------------------------------------------------------
config.py                                          9      0   100%
controller/internal_metadata.py                   25      0   100%
controller/metadata.py                             4      0   100%
main.py                                           15      0   100%
module/auth.py                                    13      0   100%
module/constant.py                                 7      0   100%
module/env.py                                     14      0   100%
module/logger.py                                  13      0   100%
module/response.py                                11      0   100%
module/schema/metadata.py                         18      0   100%
module/schema/storage.py                          10      0   100%
module/storage/local.py                           62      0   100%
module/storage/main.py                            25      0   100%
module/storage/s3.py                              74      0   100%
module/storage/storage_interface.py                1      0   100%
module/utils.py                                   95      0   100%
routers/__init__.py                                0      0   100%
routers/health.py                                  5      0   100%
routers/internal_metadata.py                      12      0   100%
routers/metadata.py                               10      0   100%
routers/router.py                                  6      0   100%
tests/__init__.py                                  0      0   100%
tests/constant.py                                  3      0   100%
tests/mock_class.py                               43      0   100%
tests/test_create_backup.py                       22      0   100%
tests/test_flatten_attribute.py                   17      0   100%
tests/test_get_metadata.py                        27      0   100%
tests/test_get_metadata_endpoint.py               29      0   100%
tests/test_healthcheck.py                          9      0   100%
tests/test_put_internal_metadata_endpoint.py      73      0   100%
tests/test_save_metadata.py                       37      0   100%
tests/test_storage_local.py                      103      0   100%
tests/test_storage_s3.py                         115      0   100%
tests/test_update_attribute.py                    44      0   100%
tests/test_update_metadata.py                     49      0   100%
tests/test_verify_token.py                        32      0   100%
tests/utils.py                                     6      0   100%
------------------------------------------------------------------
TOTAL                                           1038      0   100%
```

2023-02-01 04:15 UTC, atiqahammed-liquidx approved these changes

2023-02-02 04:27 UTC, nobelk requested changes

2023-02-02 04:27 UTC, nobelk commented on README.md
> +2. Go to the project directory and run `pip install -r requirements.txt` to install dependencies
Will the virtual environment be used?

2023-02-02 04:27 UTC, nobelk commented on controller/metadata.py
> +        return json.loads(err.json()), HTTPStatus.INTERNAL_SERVER_ERROR
Wrong error type: should be bad request/400 family of errors.

2023-02-02 04:27 UTC, nobelk commented on module/storage/interface.py
> +class StorageInterface(metaclass=abc.ABCMeta):  # pragma: no cover
Nice use of inheritance

2023-02-02 04:27 UTC, nobelk commented on module/storage/s3.py
> +        session = aioboto3.Session()
Are you able to test the S3 bucket case?

2023-02-02 04:27 UTC, nobelk commented on module/storage/interface.py
> +"""Storage interface define the abstract class for a storage.
interface.py is a too generic, use a specific name: storage_interface.py or similar

2023-02-02 04:27 UTC, nobelk commented on module/storage/interface.py
> +    async def get(self) -> bytes:
Pls add update method.
That is because, update metadata is a very common operation.

2023-02-02 04:27 UTC, nobelk commented on module/storage/local.py
> +class LocalStorage(StorageInterface):
Pls add implementation for Pinata as well

2023-02-02 04:27 UTC, nobelk commented on module/storage/local.py
> +            with open(path, "rb") as file:
Use async with aiofiles.open here.
Any IO, network calls should be async.

2023-02-02 04:27 UTC, nobelk commented on tests/test_storage_local.py
> +class TestStorageLocal(unittest.TestCase):
Pls ensure >= 95% unit test coverage.

2023-02-02 04:27 UTC, nobelk commented on README.md
> +   - `MAX_TOKEN_ID`: The maximum token ID of metadata available
Pls get it reviewed by Amjad.

2023-02-02 06:01 UTC, KY64 commented on module/storage/s3.py
> +        session = aioboto3.Session()
Yes, we do the mock test in the `tests/test_storage_s3.py` file

2023-02-02 06:01 UTC, KY64 commented on tests/test_storage_local.py
> +class TestStorageLocal(unittest.TestCase):
Yes, the test already covered 100%

2023-02-02 06:04 UTC, KY64 commented on README.md
> +2. Go to the project directory and run `pip install -r requirements.txt` to install dependencies
Yes, I've updated the step to create environment variable.
I don't upload the virtual environment in the repository because it may cause issue if the user is using more recent
Python version. Some dependencies may use absolute path which may cause issue if used by other machine
or has library issues if used in other architecture than x86 or other operating system.

So I think the better way to just add `requirements.txt` in the repository then user will run `pip install -r requirements.txt`
to install the dependencies.

2023-02-02 06:09 UTC, KY64 commented on controller/metadata.py
> +        return json.loads(err.json()), HTTPStatus.INTERNAL_SERVER_ERROR
I'll update it

2023-02-02 07:43 UTC, KY64 commented on README.md
> +   - `MAX_TOKEN_ID`: The maximum token ID of metadata available
@amjad-omnilytics could you help review it?

2023-02-02 09:23 UTC, amjad-omnilytics approved these changes

2023-02-02 09:23 UTC, amjad-omnilytics commented on main.py
> +    uvicorn.run(app, host="0.0.0.0", port=8000)
can we make the host and port configurable?

2023-02-02 09:23 UTC, amjad-omnilytics commented on routers/router.py
> +    def healthcheck():
This API will be called most frequently and consistently, so can we make this API async too?

2023-02-02 09:23 UTC, amjad-omnilytics commented on routers/metadata.py
> +    content, status_code = await metadata.get(token, logger)
need to find a way so that we do not need to pass logger instance to every method we call

2023-02-02 09:23 UTC, amjad-omnilytics commented on module/storage/main.py
> +        if storage == StorageType.S3:
Abstract Factory pattern is fine for now as there is less chance to have more than 3 Storage Type, but if it increases we can implement Factory Pattern or something better

2023-02-02 09:27 UTC, KY64 commented on main.py
> +    uvicorn.run(app, host="0.0.0.0", port=8000)
Yes, it's possible. I'll update to make it configurable

2023-02-02 09:27 UTC, KY64 commented on routers/router.py
> +    def healthcheck():
Sure, will update the commit

2023-02-02 09:29 UTC, KY64 commented on routers/metadata.py
> +    content, status_code = await metadata.get(token, logger)
I'll try, previously I faced an issue not able to use the logger instance and it gives the default UUID instead of a unique one so it's hard to trace the log.

2023-02-04 00:47 UTC, KY64 commented on module/storage/main.py
> +        if storage == StorageType.S3:
Updated here https://github.com/LiquidX-Studio/Fast-metadata-service/pull/1/commits/09207746666d0babe1df390e551f65628628f59f

2023-02-04 00:48 UTC, KY64 commented on routers/metadata.py
> +    content, status_code = await metadata.get(token, logger)
Updated here https://github.com/LiquidX-Studio/Fast-metadata-service/pull/1/commits/2f09a54a4b56963e4d9cf16814ebee555ff62a8b

2023-02-04 00:48 UTC, KY64 commented on routers/router.py
> +    def healthcheck():
Updated here https://github.com/LiquidX-Studio/Fast-metadata-service/pull/1/commits/2f09a54a4b56963e4d9cf16814ebee555ff62a8b

2023-02-04 00:49 UTC, KY64 commented on controller/metadata.py
> +        return json.loads(err.json()), HTTPStatus.INTERNAL_SERVER_ERROR
Updated here https://github.com/LiquidX-Studio/Fast-metadata-service/pull/1/commits/2f09a54a4b56963e4d9cf16814ebee555ff62a8b

2023-02-04 00:49 UTC, KY64 commented on README.md
> +2. Go to the project directory and run `pip install -r requirements.txt` to install dependencies
Updated docs https://github.com/LiquidX-Studio/Fast-metadata-service/pull/1/commits/588ad62f6645901b7b16e20bdb8403ef8c2b3ecd

2023-02-04 00:50 UTC, KY64 commented on module/storage/interface.py
> +"""Storage interface define the abstract class for a storage.
Renamed here https://github.com/LiquidX-Studio/Fast-metadata-service/pull/1/commits/2f09a54a4b56963e4d9cf16814ebee555ff62a8b

2023-02-04 00:50 UTC, KY64 commented on module/storage/local.py
> +            with open(path, "rb") as file:
Implemented here https://github.com/LiquidX-Studio/Fast-metadata-service/pull/1/commits/2f09a54a4b56963e4d9cf16814ebee555ff62a8b

2023-02-05 15:56 UTC, KY64 commented on module/storage/interface.py
> +    async def get(self) -> bytes:
Added here https://github.com/LiquidX-Studio/Fast-metadata-service/pull/1/commits/1c268f23d6b74c6c349b52a39c50d092ec133220

2023-02-28 14:11 UTC, nobelk approved these changes

2023-03-24 11:22 UTC, merged